[tool.poetry]
name = "herakles"
version = "0.1.4"
description = "Tools for working with the python jira client."
authors = ["David Bradford <david.bradford@mongodb.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/dbradf/herakles-jira-client"

[tool.poetry.dependencies]
python = "^3.7"
jira = "^2.0"
PyYaml = "^5.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3"
pytest-black = "^0.3.7"
pytest-cov = "^2.8"
pytest-flake8 = "^1.0"
pytest-mypy = "^0.4"
pytest-pydocstyle = "^2.0"
pytest-sugar = "^0.9.2"
pytest-isort = "^0.3.1"

[tool.black]
line-length = 100
target-version = ['py37']
exclude = 'setup.py'
