[tool.poetry]
name = "singleton-py3"
version = "0.1.0"
description = ""
authors = ["David Jim√©nez <davigetto@gmail.com>"]
packages = [
    { include = "singleton" }
]

[tool.poetry.dependencies]
python = ">=3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
