version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: dev/Dockerfile
    image: registry.gitlab.com/izel93/embrion/dev:0.1.6
    ports:
     - 8888
     - 22
     - 8443
    volumes:
      - ${PWD}:/app
#      - .:/embrion
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    entrypoint: "/embrion/dev/startup.sh"