[tool.poetry]
name = "deepehr"
version = "0.1.1"
description = "Deep Learning for EHR Analysis"
authors = ["yajiez <yajiez.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^0.25.3"
seaborn = "^0.9.0"
torch = "^1.3.1"
gensim = "^3.8.1"
ipykernel = "^5.1.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
